### ISSUE TITLE
Add coordinate conversion functions to PdfRenderConfig.

### ISSUE THREAD

**Issue by boan-anbo** [ajrcarey/pdfium-render#108]
Hi there! I have a new use case with the pdfium-render but I'm uncertain where to start to implement it. I wonder if you could point me to the right place.

## The feature needed:

When a user uses the common PDF box drawing tool to create a box over an area of a page like below, __this box can be used to capture the image within it (the area within the red box)__ and save it as a separate image file such as png.

It seems I could use the [page_object_image](https://github.com/ajrcarey/pdfium-render/blob/643c1d1ac1728ec196fc3bc280b86f9205415768/src/page_object_image.rs#L49), but I'm not sure how to use the annotation (the red box) to crop the area I need out of the image.

A second route I tried was through `PdfRenderConfig` which has "clip" method. But I couldn't figure out how to translate between the bound of PDF Annotation object and the `Pixels` parameters of the `clip` method.

Any pointers would be appreciated! Thanks.

![image](https://github.com/ajrcarey/pdfium-render/assets/7269717/b66d535d-0d4a-4850-bf12-c49c9a30e662)

I'm also attaching a sample PDF below.
[Extracted pages from chn.pdf](https://github.com/ajrcarey/pdfium-render/files/12744265/Extracted.pages.from.chn.pdf)

**Comment by ajrcarey** [comment]
Hi @boan-anbo , thank you for reporting the issue.

The bitmap and image functions in `PdfPageImageObject` can only render itself to a bitmap, not anything else on the page. So probably it isn't what you need.

I think your second approach is the way to go. Pdfium does provide functions for translating between bitmap pixel coordinates and page coordinates expressed in points, but `pdfium-render` doesn't expose those functions at the moment (because they've never really seemed useful or necessary - until now!). I suggest we aid translation functions to `PdfRenderConfig`; you can then use those to clip the page render to the bounding box of an annotation or a page object.

I should have time this weekend to add the new functionality for you.

**Comment by ajrcarey** [comment]
Added bindings for `FPDF_DeviceToPage()` and `FPDF_PageToDevice()` Pdfium functions, then used these to add new `PdfPage::pixels_to_points()` and `PdfPage::points_to_pixels()` coordinate system conversion functions.

The new `examples/export_clip_crop.rs` example demonstrates how to render just the area within the square annotation to a file. I believe this provides the solution you are after.

**Comment by ajrcarey** [comment]
Added WASM implementations of `FPDF_DeviceToPage()` and `FPDF_PageToDevice()`. Updated README. Ready to release as crate version 0.8.12.

**Comment by ajrcarey** [comment]
Fixed typos in new example.

**Comment by ajrcarey** [comment]
As there have been no further comments and I believe a complete solution has been provided, I am closing the issue. Feel free to re-open as necessary.

Released as part of crate version 0.8.12.

**Comment by boan-anbo** [comment]
Thanks so much! Sorry, I haven't had the opportunity to test it out on my end but will report back if there are any issues!
