### ISSUE TITLE
Text segment font and displaying on browser

### ISSUE THREAD

**Issue by reyjexter** [ajrcarey/pdfium-render#115]
What's the best way to extract or determine the font used for a given text segment and display that text on browser? The PDF uses custom fonts and different fonts can be used per page.

We are able to extract text segments of each page and display that text on browser but we aren't able to show that text using the correct font name and size. We are also able to determine the fonts used on a page but not the individual text segments.

The following code is used to extract the text segments:

```
let text_bindings = pdf_page.text().unwrap();
text_bindings
   .segments()
   .iter()
   .enumerate()
   .map(|(index, pdf_page_text_segment)| {
              // Display page text on browser here using pdf_page_text_segment.text()
   })
```

Thanks and appreciate any help with this.

**Comment by ajrcarey** [comment]
Hi @reyjexter , font properties are available on a character-by-character basis for characters within annotations, page text objects, and free-form rectangles from the PdfPageText struct. Since the text segment has a bounds() property, we can use that to retrieve characters within the bounds of the segment like so:

```
let text = page.text()?;

let chars = text.chars_inside_rect(text.segments().first()?.bounds());
```

I have pushed a small patch which adds a convenience function, PdfPageTextSegment::chars(), to make this easier. The above can be written more simply as:

`let chars = text.segments().first()?.chars()?;`

From there, you can iterate over characters in the segment and retrieve their font names, weights, sizes, colors, and other properties.

Since Pdfium collapses related text blocks into single text segments based on their font properties, we would expect all characters in a single text segment to share at least a font name and font weight, and perhaps a font size as well. This is demonstrated by the following snippet, which prints the properties of characters in segments to the console. You can adapt this to solve your browser-based problem.

```rust
use pdfium_render::prelude::*;

fn main() -> Result<(), PdfiumError> {
    let pdfium = Pdfium::new(Pdfium::bind_to_library(
        Pdfium::pdfium_platform_library_name_at_path("../pdfium/"),
    )?);

    let document = pdfium.load_pdf_from_file("../pdfium/test/text-test.pdf", None)?;

    let page = document.pages().first()?;

    let text = page.text()?;

    for (segment_index, segment) in text.segments().iter().enumerate() {
        for (char_index, char) in segment.chars()?.iter().enumerate() {
            println!(
                "Segment {} char {}: {}: font = {}, size = {}, weight = {:?}",
                segment_index,
                char_index,
                char.unicode_char().unwrap(),
                char.font_name(),
                char.scaled_font_size(),
                char.font_weight()
            );
        }
    }

    Ok(())
}

```

**Comment by ajrcarey** [comment]
As there have been no further comments, there is no indication that I can see in your question of a bug in `pdfium-render`, and I believe your question has now been answered, I am closing the issue. Feel free to reopen if your question has not been answered.

The `PdfPageTextSegment::chars()` convenience function will be included in crate release 0.8.15.

**Comment by reyjexter** [comment]
Sorry for the late reply and I can confirm that the new convenience function works properly. 

An additional question is there no way to extract a `.ttf` or `.otf` font embedded on PDF using the library? I guess this means that we will just need to make sure that we have a copy of the font file that is used on document.

Thanks

**Comment by ajrcarey** [comment]
Correct, font extraction is not possible as that would enable copyright and font licensing violations.
