### ISSUE TITLE
Statically linking pdfium

### ISSUE THREAD

**Issue by LordMZTE** [ajrcarey/pdfium-render#12]
To make my application more portable, I'd like to statically link PDFium. Could this be added to this crate?

**Comment by ajrcarey** [comment]
Hi there, thank you for your query. Can you clarify what you mean by "statically link"? Do you want to actually include Pdfium in your Rust executable when you run cargo build?

**Comment by ajrcarey** [comment]
Ok. Let me do some research on this next week and come back to you. If it's possible, it might make for an interesting optional feature.

**Comment by ajrcarey** [comment]
Ok, I've looked into this a bit.

Short answer: yes, it's possible to statically link to Pdfium at compile time, and it's no problem to implement static bindings for pdfium-render.

Longer answer: yes, it's possible, but.... :)

I am not a compiler expert, so am happy to be corrected on this. But my understanding is that, when you compile a library (like Pdfium, for instance), you make a decision at compilation time as to whether your library will be used for static linking or dynamic linking. (On linux, this results in the compiler generating you a .a file for static linking, or a .so file for dynamic linking.) Once you have a static library, you _only_ link it statically into an executable; you can't rework it so you can link to it dynamically at runtime. Likewise, once you have a dynamic library, you can _only_ link to it dynamically from an executable; you can't rework it so you can statically link to it at compile time.

Herein lies the problem. In order to statically link to Pdfium at compile time (and thus embed it in your executable), you would need a static library build of Pdfium. And as far as I can tell, most of the pre-built Pdfium libraries available aren't built statically; they're built for dynamic linking. For instance, all the builds I currently recommend at https://github.com/bblanchon/pdfium-binaries/releases are dynamic libraries - they can't be used for static linking.

The repo https://github.com/paulocoutinhox/pdfium-lib/releases does publish static builds for ios and macos, and I think the reason they've done this is that it's much easier to persuade Xcode to link against a static build at compile time than to use a dynamic library at runtime. But all other platform releases I can find publish dynamic libraries, not static libraries.

I think it's highly likely you will need to build Pdfium statically yourself if you want to do this. The good news is there are build scripts for doing so in those two repos I mentioned; you just need to change the build flags to generate a static library rather than a dynamic one. (I _think_ it's as simple as changing the "pdf_is_standalone = true" ninja build flag to "pdf_is_standalone = false".)

So, I'm going to add the option for binding to a statically-linked Pdfium library to pdfium-render, because it's genuinely helpful to have that option when compiling for ios and macos. But for all other platforms, I think you're still better off using dynamic linking and just shipping a libpdfium.so alongside your executable, because to link statically you're probably going to have to build Pdfium yourself.

I think the idea of having pdfium-render build Pdfium for you is outside the goals of this crate. I am open to having a crate feature where pdfium-render sends a message to cargo to link in a pre-built Pdfium static library, since this means you wouldn't need to muck around with a custom build script yourself.

**Comment by ajrcarey** [comment]
The static bindings, and the feature to link to a pre-build Pdfium static library at compile time, will be included in release 1.57 later on this week or early next. (I need to finish 1.56 and get that out first!)

**Comment by ajrcarey** [comment]
Then you are welcome to write a build.rs for your application to do the build of Pdfium.

There is nothing in my proposal specific to any particular platform. If you can build a static library of Pdfium for Linux, for instance, then you'll be able to access it in pdfium-render at runtime. I am simply saying you'll need to build it yourself, that's all.

**Comment by ajrcarey** [comment]
Added static binding implementation and optional crate `static` feature. Added `PDFIUM_STATIC_LIB_PATH` support during build.rs; pdfium-render will output the cargo flags necessary to link a Pdfium static build into the Rust executable if `PDFIUM_STATIC_LIB_PATH` is set. Updated documentation. Bumped crate version to 0.5.7. Published to crates.io.

**Comment by ajrcarey** [comment]
Hi @LordMZTE, it's been a while since we discussed this but based on another contribution I have opened tracking issue #53 to consider options for (eventually) adding some automation of the building of Pdfium to `pdfium-render`. In the meantime, an outline of how to build Pdfium, including a script that may be useful, is provided in that tracking issue. I thought you might like to know.
