### ISSUE TITLE
Add text objects editing functionality

### ISSUE THREAD

**Issue by AbdesamedBendjeddou** [ajrcarey/pdfium-render#17]
The easiest way IMO to edit a text object in a pdf file is if we can directly edit the raw object 

`BT
/F13 12 Tf
288 720 Td
(ABC) Tj
ET`
As a side effect we can easily edit many other properties of the text object, however I don't know how easy it is to implement this or if it's even possible. especially that I don't exactly understand how are document level objects and cross references tables and other stuff that I may not know about relate to the content of the text object

**Comment by AbdesamedBendjeddou** [comment]
Yes, I want to be able update some properties like boldness but I don't know if this is possible withing the same object. like can the same text object have some bold words and other words that are regular. If not then we'll need to implement a way to replace one text object with multiple text objects I don't know if that is feasible

**Comment by ajrcarey** [comment]
I'm not an expert, but the impression I have from reading the PDF Reference Manual is that each text object has a single font specification. The size of the text fragment (specified by TJ) can be adjusted because the text rendering matrix can be used to apply a scaling effect, but the weight of the font - i.e. whether it is bold or not - is a property of the font, not the text, so cannot change within a single text object.

It certainly seems that's what the Pdfium authors thought as well, because each page text object is linked to a single font specification. If you want to edit some text _and_ change the font at the same time (even if it's just the font weight you are changing), I think you'll need to split the text object into two and position them appropriately.

I don't think it's necessarily a problem to add new text objects to a page - certainly Pdfium lets you do that - but you might find it fiddly to position them correctly, that's all.

**Comment by ajrcarey** [comment]
(For reference, the Pdfium functions for editing/creating page text objects are FPDFPageObj_CreateTextObj and FPDFText_SetText, if you want to look at them. Documentation isn't great outside just reading the source code at https://pdfium.googlesource.com/pdfium/+/HEAD/public/fpdf_edit.h.)

**Comment by ajrcarey** [comment]
No problem. I'm nearly done with the initial editing infrastructure. Can you provide a one-page PDF sample that demonstrates what you're trying to achieve? It would help me design the functions that can best achieve what you're trying to do.

**Comment by AbdesamedBendjeddou** [comment]
Here is the PDF you requested. The first paragraph is what the original PDF would be, the second paragraph shows what the edited PDF should look like. Let me know if you need anything else
[sample.pdf](https://github.com/ajrcarey/pdfium-render/files/8791598/sample.pdf)

**Comment by ajrcarey** [comment]
Thanks for that. So it's literally just the formatting you want to change, then?

Running the examples/objects.rs example across this file gives us a report on how the text objects are defined in the sample. We can see there's at least one for each line, and then where the font weight changes, there's a change in text object. So this confirms our earlier theory that each text object is limited to a single font setting which includes the weight.

The old iText library, from which the current OpenPDF Java library is inherited, has the concept of a Paragraph which can include multiple elements (including individual text objects), all of which are positioned and manipulated as a block rather than individually. I think we'll need to have something like this to make your job as simple as possible. The basic idea would be:

* Create a PdfPageObjectParagraph from the text objects that make up your original text. Pdfium supports retrieving page objects based on whether they fall inside a rectangular region, which would probably be the simplest way in this particular case - select all text objects inside a certain region, then create a PdfPageObjectParagraph out of them.
* Specify how you want the Paragraph to change dimensions and position as the content within changes (since, even if you just change the font weights, it's possible for the line breaks within the paragraph to change and thus the size of the paragraph to change)
* Iterate through the raw text in the Paragraph, applying different font styles as you wish - internally, the Paragraph will break up text objects into new ones to acommodate the changes in styles
* Replace the existing Paragraph in your document with the new Paragraph
* Save your document to a file.

My proposal is to publish all the infrastructure stuff, including all the mutable bindings, as crate version 0.7.0, then add the Paragraph feature for you in version 0.7.1. I think it's realistic to get it all done in the next week or so if you can wait that long.

**Comment by AbdesamedBendjeddou** [comment]
I was thinking of:

- Iterate through every text object in every page in the original document. extracting the text and formatting and position
- Apply the changes, resulting in new Child Objects
- iterate through every object, remove it from the document and place the new child objects
- the first Child Object will be placed in the same position as the original object and the remaining Child Objects will be placed according to the bounds of the previous Child Object

but I think your idea is better, it makes things really simple. Please take your time. I'm here if you want help testing the new features

**Comment by ajrcarey** [comment]
Yes, that approach sounds like it would work. You'd have to position everything manually, that's all.

I'm going to try to get 0.7.0 out some time tomorrow (Monday), and that should include everything you need to try your approach, if you want to try it. In the meantime, I'll work on 0.7.1.

Pdfium lets you mutate objects willy-nilly once you have handles to them. It's a big reason, I think, why Pdfium isn't thread-safe it is current form and I'd like for pdfium-render's high-level interface to try to avoid that. So I am trying to adopt an approach where the high-level interface doesn't let you mutate any existing page object - you can only set a page object's properties once, at the time you create it. It is a bit more strict but it is much easier to reason about, I think.

It shouldn't affect your approach too much, it just means instead of applying changes to any existing text object, you'd have to create new ones. You may have been going to do that anyway.

**Comment by ajrcarey** [comment]
Ok, I'm going to work a bit more on the documentation before I publish a new crate version, but I've pushed a commit now that should let you make some progress. You can access it by referencing pdfium-render as a git dependency in your Cargo.toml.

Here's some sample code to get you underway. It just alternates the font of every word - you want something a bit more specific than that, I think. But it should give you the general idea.

`
use pdfium_render::prelude::*;
use std::fs::File;

fn main() {
    // For general comments about pdfium-render and binding to Pdfium, see comments in export.rs.

    let bindings = Pdfium::bind_to_library(Pdfium::pdfium_platform_library_name_at_path("./"))
        .or_else(|_| Pdfium::bind_to_system_library());

    match bindings {
        Ok(bindings) => {
            let pdfium = Pdfium::new(bindings);

            // Create a new blank document containing a single page with the desired sample text.

            let document = pdfium.create_new_pdf().unwrap();

            let mut pages = document.pages();

            let mut page = pages.create_page_at_start(PdfPagePaperSize::a4()).unwrap();

            // Desired sample text:

            let sample_text = vec!(
                "TITLE HERE",
                "",
                "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum",
                "has been the industry's standard dummy text ever since the 1500s, when an unknown",
                "printer took a galley of type and scrambled it to make a type specimen book. It has",
                "survived not only five centuries, but also the leap into electronic typesetting, remaining",
                "essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets",
                "containing Lorem Ipsum passages, and more recently with desktop publishing software like",
                "Aldus PageMaker including versions of Lorem Ipsum.",
            );

            // Add the sample text to the page. We create a separate text object
            // for each line in the sample text.

            let regular_font = PdfFont::helvetica(&document);

            let bold_font = PdfFont::helvetica_bold(&document);

            let font_size = PdfPoints::new(12.0);

            let line_spacing = font_size * 1.5;

            let line_left = PdfPoints::new(50.0);

            let mut line_top = PdfPoints::new(700.0);

            for (index, line) in sample_text.iter().enumerate() {
                let font = {
                    // Make the first line bold, all other lines regular.

                    if index == 0 {
                        &bold_font
                    } else {
                        &regular_font
                    }
                };

                page.objects_mut()
                    .create_text_object(line_left, line_top, line, font, font_size)
                    .unwrap();

                line_top -= line_spacing;
            }

            // Save the initial state to a file.

            document
                .save_to_writer(File::create("before.pdf").unwrap())
                .unwrap();

            // Now we transform the text objects on the page. We retrieve all objects on the page,
            // filtering out just the text objects. For each retrieved text object we split the
            // text into separate words, then iterate through each word, creating a separate text
            // object for each and applying bold font to alternate words. We place the newly
            // created text objects beneath the original set of text objects.

            // We cannot iterate over the text objects in the page while simultaneously holding
            // a mutable reference to that page. Instead, we build a list of new text objects
            // separately, then add them all to the page in a single operation.

            let mut new_objects = Vec::new();

            let mut bold = true;

            let word_separation = PdfPoints::new(4.0);

            for object in page.objects().iter() {
                if let Some(line) = object.as_text_object() {
                    let line_left = object.bounds().unwrap().left;

                    let line_top = object.bounds().unwrap().top - PdfPoints::new(400.0);

                    let mut word_left = line_left;

                    line.text()
                        .split(" ")
                        .map(|word| {
                            // Create a new text object for this word.

                            let mut object = PdfPageTextObject::new(
                                &document,
                                word,
                                if bold { &bold_font } else { &regular_font },
                                font_size,
                            )
                            .unwrap();

                            // Set the position of this word.

                            object.translate(word_left, line_top);

                            // Set the start position of the next word.

                            word_left += object.width().unwrap() + word_separation;

                            // Switch the bold status for the next word.

                            bold = !bold;

                            object
                        })
                        .for_each(|object| new_objects.push(object));
                }
            }

            // Add all new objects to the page.

            for new_object in new_objects.drain(..) {
                page.objects_mut().add_text_object(new_object).unwrap();
            }

            // Save the result to a file.

            document
                .save_to_writer(File::create("after.pdf").unwrap())
                .unwrap();
        }
        Err(err) => eprintln!("Error loading pdfium library: {:#?}", err),
    }
}
`

It creates both a before.pdf and an after.pdf. Attached is an example of the after.pdf
[after.pdf](https://github.com/ajrcarey/pdfium-render/files/8800611/after.pdf)
.

**Comment by AbdesamedBendjeddou** [comment]
Hi, I really can't thank you enough, I think this is all what I need. I'm testing it now. 
btw there is a little error when compiling the library 
`src\utils.rs, line 130`
`mismatched types expected `u32`, found `u64``

**Comment by ajrcarey** [comment]
No problem, happy to help.

Regarding that error: can I ask what architecture you're compiling on?

I noticed the same thing when compiling to WASM. (I'm working on the WASM bindings at the moment.)

I think you can fix it for all architectures by changing line 127 to this:

`let content_length = reader.seek(SeekFrom::End(0)).unwrap_or(0) as c_ulong;`

**Comment by ajrcarey** [comment]
Updated and reviewed generated documentation. Updated READMEs. Updated examples. Added WASM binding implementations.

**Comment by ajrcarey** [comment]
Waiting to complete #12 before publishing new crate version 0.7.0.
