### ISSUE TITLE
Marshall calls to Pdfium to make pdfium-render thread-safe.

### ISSUE THREAD

**Issue by nagato-chan** [ajrcarey/pdfium-render#20]
At the moment multiple rendering will caused a memory error, which stopped from rendering multiple documents at the same time.

**Comment by ajrcarey** [comment]
Hello, thank you for opening this issue.

Pdfium makes absolutely no guarantees about thread safety, which means it's hard for pdfium-render to provide much in the way of guarantees either. That said, if there's a way to safely provide multhreaded rendering, I'd be happy to do so. Can you provide more information about what you're trying to do, ideally with a code sample that demonstrates the problem?

**Comment by nagato-chan** [comment]
I am trying to make a document rendering backend which can open multiple rendering pipeline at one time. It is a must to make it parallel and multi-threading.

**Comment by ajrcarey** [comment]
Yes, I surmised as much. Let me put my query another way: what is the approach you are taking at the moment that _isn't_ working? Again, a code sample would be best if at all possible.

Absent any further information, there isn't much I can do help you. It is very hard for me to help you without seeing your code.

I reiterate that Pdfium makes no guarantees around multi-threading.

**Comment by ajrcarey** [comment]
(One further comment: if you are creating a new Pdfium object in each thread, you will definitely get into big trouble because when each object exits scope it will call FPDF_DestroyLibrary(), which will interefere with any Pdfium objects still in use in other threads. So you definitely want to create a single Pdfium object, then share it across threads, only destroying it once all threads have completed their tasks. _In theory_, if you shared a single Pdfium object, you _might_ be able to perform certain read-only operations in multiple threads simultaneously.)

**Comment by ajrcarey** [comment]
I imagine you want to do something like this:

```
use image::ImageFormat;
use pdfium_render::prelude::*;
use rayon::prelude::*;

fn main() -> Result<(), PdfiumError> {
    // Create a single set of bindings that are shared across multiple threads.

    let pdfium = Pdfium::new(
        Pdfium::bind_to_library(Pdfium::pdfium_platform_library_name_at_path("./"))
            .or_else(|_| Pdfium::bind_to_system_library())?,
    );

    // Set shared rendering settings that we'll apply to every page in every source file.

    let render_config = PdfBitmapConfig::new()
        .set_target_width(2000)
        .set_maximum_height(2000)
        .rotate_if_landscape(PdfBitmapRotation::Degrees90, true);

    // Launch separate, simultaneous rendering jobs on different threads using rayon::par_iter().

    vec![
        "test/export-test.pdf",
        "test/form-test.pdf",
        "test/create-test.pdf",
        "test/path-test.pdf",
    ]
    .iter() // Change to .par_iter() to make Pdfium segfault
    .for_each(|path| assert!(render(&pdfium, &render_config, path).is_ok()));

    println!("All done!");

    Ok(())
}

fn render(pdfium: &Pdfium, render_config: &PdfBitmapConfig, path: &str) -> Result<(), PdfiumError> {
    let document = pdfium.load_pdf_from_file(path, None)?;

    println!("{} is {:?}", path, document.version());
    println!("{} pages in {}", document.pages().len(), path);

    for (index, page) in document.pages().iter().enumerate() {
        println!("Rendering page {} of {}", index, path);

        page.get_bitmap_with_config(render_config)?
            .as_image()
            .as_rgba8()
            .ok_or(PdfiumError::ImageError)?
            .save_with_format(format!("{}-{}.jpg", path, index), ImageFormat::Jpeg)
            .map_err(|_| PdfiumError::ImageError)?;
    }

    Ok(())
}
```

You will need to change line 41 of bindings.rs to read:

pub trait PdfiumLibraryBindings: Send + Sync {

The sample works perfectly as written above, but exchange the .iter() for .par_iter() on line 28 and Pdfium will quickly crash. gdb indicates the crash is deep within Pdfium's memory allocation code. I don't think there's anything I can do about this.

In theory you could manually marshall calls to Pdfium by locking and unlocking a mutex, but that defeats the purpose of parallel processing.

I strongly recommend you use parallel processes rather than threads, as recommended by the Pdfium authors themselves at https://groups.google.com/g/pdfium/c/kyIdh_J4csg/m/K1LvfPiHDwAJ, or use another thread-safe Pdf library. Pdfium can't safely do what you're asking.

**Comment by ajrcarey** [comment]
Absent any further details or sample code from you, I propose to follow the same strategy as the VIPS (libvips) library at https://github.com/libvips/libvips/issues/1275, namely that all calls to Pdfium are marshalled via a mutex. This would at least make pdfium-render safe to use in a multi-threaded program, even if it didn't make a difference in performance.

**Comment by nagato-chan** [comment]
Thanks for the commit! Appreciate for your great work!

**Comment by ajrcarey** [comment]
My current plan is for the multi-threaded marshalling to be placed behind a crate feature ("threads" or similar), since I believe using a mutex imposes a small performance penalty (from locking and unwrapping the mutex), so I do not think it should be the default.

I expect the new feature to be published in version 0.7.7.

**Comment by ajrcarey** [comment]
Initially I thought it would be possible to marshall _any_ call to Pdfium from different threads sequentially by using a global mutex, but it turns out it's worse than that; Pdfium will still randomly segfault on any call that involves memory allocation or deallocation. The only way to make it work is to wrap the entire library in a mutex which is locked on the first call to FPDF_InitLibrary() and then not released until FPDF_DestroyLibrary(). This is much less granular than I was hoping for, but it does work. The first thread to call Pdfium::new() will block all other threads until the created Pdfium struct falls out of scope. The updated sample now becomes:

```
use image::ImageFormat;
use pdfium_render::prelude::*;
use rayon::prelude::*;
use std::thread;

fn main() -> Result<(), PdfiumError> {
    // Launch separate, simultaneous rendering tasks on different threads using rayon::par_iter().
    // In theory, all tasks should execute concurrently; in practice, pdfium-render will force
    // threads to block in order to maintain thread-safe access to Pdfium.

    vec![
        "test/export-test.pdf",
        "test/form-test.pdf",
        "test/create-test.pdf",
        "test/path-test.pdf",
    ]
    .par_iter() // rayon will spawn a separate thread for each task
    .for_each(|path| {
        assert!(render(
            &PdfBitmapConfig::new()
                .set_target_width(2000)
                .set_maximum_height(2000)
                .rotate_if_landscape(PdfBitmapRotation::Degrees90, true),
            path
        )
        .is_ok())
    });

    println!("All done!");

    Ok(())
}

fn render(render_config: &PdfBitmapConfig, path: &str) -> Result<(), PdfiumError> {
    // Render each page in the document at the given path out to a JPG file, using the
    // given bindings and rendering configuration.

    let pdfium = Pdfium::new(
        Pdfium::bind_to_library(Pdfium::pdfium_platform_library_name_at_path("./"))
            .or_else(|_| Pdfium::bind_to_system_library())?,
    );

    let document = pdfium.load_pdf_from_file(path, None)?;

    println!(
        "{:?}: {} is version {:?}",
        thread::current().id(),
        path,
        document.version()
    );
    println!(
        "{:?}: {} pages in {}",
        thread::current().id(),
        document.pages().len(),
        path
    );

    for (index, page) in document.pages().iter().enumerate() {
        println!(
            "{:?}: Rendering page {} of {}",
            thread::current().id(),
            index,
            path
        );

        page.get_bitmap_with_config(render_config)?
            .as_image()
            .as_rgba8()
            .ok_or(PdfiumError::ImageError)?
            .save_with_format(format!("./{}-{}.jpg", path, index), ImageFormat::Jpeg)
            .map_err(|_| PdfiumError::ImageError)?;
    }

    Ok(())
}
```

This works correctly without Pdfium crashing by blocking all threads in sequence. So, again, it completely negates any performance benefit from using multithreading. But it does prevent Pdfium from completely crashing your application.

**Comment by ajrcarey** [comment]
Updated documentation. Bumped crate version to 0.7.7. Published to crates.io.
