### ISSUE TITLE
iterate over a mutable reference of a page

### ISSUE THREAD

**Issue by AbdesamedBendjeddou** [ajrcarey/pdfium-render#23]
Trying to apply this approach I mentioned in issue #17 :
> - Iterate through every text object in every page in the original document. extracting the text and formatting and position
> - Apply the changes, resulting in new Child Objects
> - iterate through every object, remove it from the document and place the new child objects
> - the first Child Object will be placed in the same position as the original object and the remaining Child Objects will be placed 
according to the bounds of the previous Child Object

I can't seem to find a way to iterate over a mutable reference of a page, I'm trying to delete the original text objects, and insert the new child objects.
```rust
pages.iter().for_each(|page|{          
        page.objects_mut().iter().for_each(|object|{       //cannot borrow page as mutable 
            if let Some(object_text) = object.as_text_object() {
                page.objects_mut().delete_object(object);           //cannot borrow page as mutable 
            }
        })
    })
```
Can you please provide an example?

**Comment by ajrcarey** [comment]
Yes, as I noted in https://github.com/ajrcarey/pdfium-render/issues/17#issuecomment-1141457408 it is tricky to iterate over the page objects while simultaneously mutating them.

The new PdfPageGroupObject added in 0.7.2 makes this easier. I have added a function in 0.7.4 that can remove all the objects in a group from the containing page in a single step. This makes it easier to iterate, transform, and delete:

```
use pdfium_render::prelude::*;

fn main() -> Result<(), PdfiumError> {
    let pdfium = Pdfium::new(
        Pdfium::bind_to_library(Pdfium::pdfium_platform_library_name_at_path("./"))
            .or_else(|_| Pdfium::bind_to_system_library())?,
    );

    // Create a new document containing a single page with the desired sample text.

    let document = pdfium.create_new_pdf().unwrap();

    let mut pages = document.pages();

    let mut page = pages.create_page_at_start(PdfPagePaperSize::a4()).unwrap();

    // Desired sample text:

    let sample_text = vec!(
            "TITLE HERE",
            "",
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum",
            "has been the industry's standard dummy text ever since the 1500s, when an unknown",
            "printer took a galley of type and scrambled it to make a type specimen book. It has",
            "survived not only five centuries, but also the leap into electronic typesetting, remaining",
            "essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets",
            "containing Lorem Ipsum passages, and more recently with desktop publishing software like",
            "Aldus PageMaker including versions of Lorem Ipsum.",
        );

    // Add the sample text to the page. We create a separate text object
    // for each line in the sample text.

    let regular_font = PdfFont::helvetica(&document);

    let bold_font = PdfFont::helvetica_bold(&document);

    let font_size = PdfPoints::new(12.0);

    let line_spacing = font_size * 1.5;

    let line_left = PdfPoints::new(50.0);

    let mut line_top = PdfPoints::new(700.0);

    for (index, line) in sample_text.iter().enumerate() {
        let font = {
            // Make the first line bold, all other lines regular.

            if index == 0 {
                &bold_font
            } else {
                &regular_font
            }
        };

        page.objects_mut()
            .create_text_object(line_left, line_top, line, font, font_size)?;

        line_top -= line_spacing;
    }

    document.save_to_file("./before.pdf")?;

    // The document now holds the sample text we wish to transform.

    // We create two groups of text objects. The first group contains all the text objects we want
    // to replace. The second group will contain our replacement objects. We iterate over each object
    // in the first group, adding replacement text objects to the second group reflecting our
    // transformation of the original text. We then delete the objects in the first group from the page,
    // leaving only the transformed objects.

    let mut bold = true;

    let word_separation = PdfPoints::new(4.0);

    for page in document.pages().iter() {
        // Create the first group by selecting all text objects on the page.

        let mut original = PdfPageGroupObject::new(&page, |object| {
            object.object_type() == PdfPageObjectType::Text
        })?;

        // Create the second, empty, group.

        let mut transformed = PdfPageGroupObject::empty(&page);

        // For each line of text in the first group...

        for object in original.iter() {
            if let Some(line) = object.as_text_object() {
                let line_left = object.bounds().unwrap().left;

                let line_bottom = object.bounds().unwrap().bottom;

                let mut word_left = line_left;

                // ... split each word into a new text object, alternating between bold and regular font weight,
                // and add the new text object to our second group.

                for word in line.text().split(" ") {
                    // Create a new text object for this word.

                    let mut object = PdfPageTextObject::new(
                        &document,
                        word,
                        if bold { &bold_font } else { &regular_font },
                        font_size,
                    )
                    .unwrap();

                    // Set the position of this word.

                    object.translate(word_left, line_bottom)?;

                    // Set the start position of the next word.

                    word_left += object.width().unwrap() + word_separation;

                    // Switch the bold status for the next word.

                    bold = !bold;

                    transformed.push(&mut object.into())?;

                    // Because the page has automatic content regeneration switched on
                    // (the default), adding the new object into the transformed group is enough
                    // to add it to the page. We don't need to do anything special.
                }
            }
        }

        // With all transformed objects now on the page, we can remove the originals.

        original.remove_objects_from_page()?;
    }

    document.save_to_file("./after.pdf")?;

    Ok(())
}
```

Make sure you update to crate version 0.7.4 before running the sample. It will generate two output files: `before.pdf` that shows the original state (created here by hand, but I guess you have some pre-existing source files you will operate on) and `after.pdf` that shows the original text objects removed with the replaced text objects taking their place.

The example shows using two groups, but probably you only need one, to hold the original text objects; the replacements can probably be added directly to the page using `page.objects_mut().create_text_object(...)`.

I tend to recommend using loops rather than closures for iterating over the Pdfium objects because it is harder to propagate `Result<_, PdfiumError>` when using closures. You may find yourself using `.unwrap()` a lot inside closures!

**Comment by AbdesamedBendjeddou** [comment]
It seems that there some problems

The first error occurs when applying translate() method on the child object. error was not clear so I tried to comment out the line it gave another error when pushing the object to the transformed groupe. This was using my testing pdf file so I used the example you provided in issue #17 to have an easier time debugging. I got what I think is the same issue

```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PdfiumLibraryInternalError(Unknown)', src\lib.rs:62:22
```
line 62 was
```rust
 page.objects_mut() .create_text_object(line_left, line_top, line, font, font_size).unwrap();
```
This example worked fine in version 0.7.0.

the second problem using the example you provided above I was not able to create the before.pdf the error is not clear (this was using only this part of the code:
```rust
use pdfium_render::{prelude::*, page_object_group::PdfPageGroupObject};

fn sample() -> Result<(), PdfiumError> {
    let pdfium = Pdfium::new(
        Pdfium::bind_to_library(Pdfium::pdfium_platform_library_name_at_path("./"))
            .or_else(|_| Pdfium::bind_to_system_library())?,
    );

    // Create a new document containing a single page with the desired sample text.

    let document = pdfium.create_new_pdf().unwrap();

    let mut pages = document.pages();

    let mut page = pages.create_page_at_start(PdfPagePaperSize::a4()).unwrap();

    // Desired sample text:

    let sample_text = vec!(
            "TITLE HERE",
            "",
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum",
            "has been the industry's standard dummy text ever since the 1500s, when an unknown",
            "printer took a galley of type and scrambled it to make a type specimen book. It has",
            "survived not only five centuries, but also the leap into electronic typesetting, remaining",
            "essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets",
            "containing Lorem Ipsum passages, and more recently with desktop publishing software like",
            "Aldus PageMaker including versions of Lorem Ipsum.",
        );

    // Add the sample text to the page. We create a separate text object
    // for each line in the sample text.

    let regular_font = PdfFont::helvetica(&document);

    let bold_font = PdfFont::helvetica_bold(&document);

    let font_size = PdfPoints::new(12.0);

    let line_spacing = font_size * 1.5;

    let line_left = PdfPoints::new(50.0);

    let mut line_top = PdfPoints::new(700.0);

    for (index, line) in sample_text.iter().enumerate() {
        let font = {
            // Make the first line bold, all other lines regular.

            if index == 0 {
                &bold_font
            } else {
                &regular_font
            }
        };

        page.objects_mut()
            .create_text_object(line_left, line_top, line, font, font_size)?;

        line_top -= line_spacing;
    }

    document.save_to_file("before.pdf")?;
Ok(())
```

```rust
Error: PdfiumLibraryInternalError(Unknown)
error: process didn't exit successfully: `target\debug\bionic-pdf.exe` (exit code: 1)
```

**Comment by AbdesamedBendjeddou** [comment]
Another problem I forgot to mention is when I commented out translate() and tansformed.push(....) to check if the child objects have been created successfully. I could not extract the text from them. object.text() returns an empty string. 

A note I'd like to add is I was able to remove the text objects from my testing pdf and save the file. so I think it is possible to save an edited existing pdf but creating a new one will cause an error

**Comment by ajrcarey** [comment]
This is very strange. I can create a new Cargo project and run both examples perfectly - both the full sample I provided at https://github.com/ajrcarey/pdfium-render/issues/23#issuecomment-1152964627, and the shorter sample you posted at https://github.com/ajrcarey/pdfium-render/issues/23#issuecomment-1153032572. This suggests there must be a difference in our runtime environments. What versions of rustc and Pdfium are you using? Are you using a system-provided Pdfium library, or are you binding to a Pdfium library you are placing at a known location? What version is it?

`PdfiumError` implements `Debug`, so rather than unwrapping an error and crashing your program, you can print an error like this:

`println!("{:?}", err);`

Pdfium does not commit objects to the page (and therefore the document) until PDF content streams are regenerated. This process does not happen automatically, it must be triggered by a call to `FPDFPage_RegenerateContent()`. pdfium-render calls this function for you automatically as you add, update, and delete objects from a page, so you normally don't have to worry about regenerating content manually. (You can change this setting if you prefer to regenerate content manually, e.g. if you are adding thousands of objects to a page and regenerating content after adding each one is too slow.) When working with a `PdfPageGroupObject`, the `push()` function handles the regeneration of content. So by commenting out `transformed.push()`, you are also preventing the new objects from being committed to the page. As the documentation for `PdfPageTextObject::text()` clearly states, retrieval of text does not work if a text object is not committed to a page because all text retrieval in Pdfium is handled by the page, not the object. (I have no idea why, but that's the way it is.) This is why you cannot retrieve text from your object after you have created it. Place the object on a page, and text retrieval should work fine.

**Comment by AbdesamedBendjeddou** [comment]
It seems that the problem only happens on Windows, both the sample program and my program compiled on WSL. I was able to get the desired output on the sample pdf but not on other pdf files but that's another problem. I will open an issue for it after investigating more.
I'm using the latest version of pdfium downloaded from the binaries repo and the latest stable rust on windows 11 x86-64 machine. tell me If you want more information.
Should I open a new Issue since this is not related to the current one? this one should be closed as resolved

**Comment by ajrcarey** [comment]
Good idea, let's close this issue and yes please open another one for your Windows-specific stuff, I'm quite curious about that. Obviously everything _should_ work identically on all platforms, including WASM.
