### ISSUE TITLE
Add bindings and functions to access segments of page path objects, font glyphs, and clip paths.

### ISSUE THREAD

**Issue by chingham** [ajrcarey/pdfium-render#55]
PDFIUM allows access to Path's points to extract vector data
Base API are:
```
FPDFPathObj_CountPoints
FPDFPathObj_GetPointType
FPDFPathObj_GetPointX
FPDFPathObj_GetPointY
```

Would be very nice to have access to this in pdfium-render, in an API that can look like this:

```
for i in 0..path.points_count() {
    let type = path.get_point_type(i);
    match type {
        PdfPagePathObject::POINT_TYPE_MOVETO => {
            let x = path.get_point_x(i, 0);
            let y = path.get_point_y(i, 0);
        },
        PdfPagePathObject::POINT_TYPE_LINETO => {
            let x = path.get_point_x(i, 0);
            let y = path.get_point_y(i, 0);
        },
        PdfPagePathObject::POINT_TYPE_BEZIERTO => {
            let x1 = path.get_point_x(i, 0);
            let y1 = path.get_point_y(i, 0);
            let x2 = path.get_point_x(i, 1);
            let y2 = path.get_point_y(i, 1);
            let x3 = path.get_point_x(i, 2);
            let y3 = path.get_point_y(i, 2);
        },
        ...
    }
}
```

Or even better:

```
for point in path.points() {
    match point {
        PdfPagePathObjectPoint::MoveTo(x, y) => {},
        PdfPagePathObjectPoint::LineTo(x, y) => {},
        PdfPagePathObjectPoint::BezierTo(x1, y1, x2, y2, x3, y3) => {},
        ...
    }
}
```

**Comment by chingham** [comment]
There seem to be these APIs too, a bit different:

```
FPDF_PATHSEGMENT FPDFPath_GetPathSegment(FPDF_PAGEOBJECT path, int index);
FPDF_BOOL FPDFPathSegment_GetPoint(FPDF_PATHSEGMENT segment, float* x, float* y);
int FPDFPathSegment_GetType(FPDF_PATHSEGMENT segment);
FPDF_BOOL FPDFPathSegment_GetClose(FPDF_PATHSEGMENT segment);
```

**Comment by ajrcarey** [comment]
Hi @chingham, thank you for raising the issue and I'm very happy to help.

Whereabouts are you seeing the FPDFPathObj_*Point*() functions defined? The only reference I can find online is in Foxit's proprietary SDK, not in Pdfium. (Foxit developed the core of Pdfium first, before it was Pdfium; Google then took over that core, renamed it Pdfium, open sourced it, and Foxit's closed-source library and Pdfium have diverged ever since.)

I am very happy to add bindings for the FPDFPathSegment_*() functions and add an API to support them in pdfium-render. I like the look of your second suggested API. I'll look into this over the weekend and report back with progress.

In the meantime, if you have a specific sample file you are trying to work with, and a specific object you're trying to interact with, please do share it if you can, so I have something to test against.

**Comment by chingham** [comment]
Hi,

Yes sorry, I found FPDFPathObj by searching the web I didn't pay attention to the fact that it was not in Pdfium
FPDFPathSegment in the other hand is the API we should in that case

Here is a sample PDF file with some shapes in it
[shapes.pdf](https://github.com/ajrcarey/pdfium-render/files/9836675/shapes.pdf)

Thanks, you're awesome :)

**Comment by ajrcarey** [comment]
Ok, I've made some changes that will hopefully be helpful. Because they have not been released yet, you will need to add `pdfium-render` as a git dependency in your project's `Cargo.toml` to try them.

Having looked at the `FPDFPathSegment_*()` functions more closely now, I can see that it is not possible to reproduce your second suggested API exactly. This is mostly because Pdfium only allows you to retrieve the final destination point of each segment, not any other information about the segment. For instance, for a bezier curve segment, Pdfium does not provide any way to retrieve the control points of the curve. Hopefully there is still some use to it, though.

`examples/segments.rs` demonstrates how to use the new functionality. You can also `match` on `PdfSegment::segment_type()` if you wish, although since there is no difference in the properties available for each segment type there may be little point.

I have added your sample PDF to the repo as `test/segments-test.pdf`.

All comments and problem reports welcome.

**Comment by ajrcarey** [comment]
Pdfium uses path segments in two other situations: when working with individual font glyphs, and when working with clip paths. Added segment support to `PdfFont`. Started implementation of `PdfClipPath` with a view to completing that for crate version 0.7.25.

**Comment by ajrcarey** [comment]
Added `FPDFClipPath_CountPathSegments()`, `FPDFClipPath_GetPathSegment()`, `FPDFPath_CountSegments()`, `FPDFPath_GetPathSegment()`, and `FPDFPathSegment_*()` functions to PdfiumLibraryBindings. Added `PdfFontGlyphs` and `PdfPagePathObjectSegments` collections. Added accessor functions`PdfFont::glyphs()` and `PdfPagePathObject::segments()`. Added the `PdfPathSegments` trait. Began work on a `PdfClipPath` object. Added new `examples/segment.rs`. Updated `README.md`. Bumped crate version to 0.7.24.

**Comment by ajrcarey** [comment]
As there have been no further comments, publishing as crate version 0.7.24.
