### ISSUE TITLE
'static requirement on pdfium.load_pdf_from_reader

### ISSUE THREAD

**Issue by bavardage** [ajrcarey/pdfium-render#81]
I was wondering if you had any thoughts on the 'static lifetime requirement for load_pdf_from_reader?

inside a function I'm trying to create a reader (e.g. load via http), load the pdf, extract some metadata and return

conceptually this feels like it should be possible, as long as the reader lives longer than the document

I haven't yet attempted to relax this lifetime constraint - was curious if there are reasons why this is doomed before I try to make a PR

**Comment by ajrcarey** [comment]
Hi @bavardage , good question! Playing around with it a bit, it looks like the reason for the `'static` lifetime is due to the requirements of boxing up the reader in `crate::utils::get_pdfium_file_accessor_from_reader()`. I don't see any other reason for the `'static`. If you can find a way around that, I'm very happy to take a PR.

I couldn't see an immediate solution in the 30 or so minutes I spent looking at it, but that doesn't mean there isn't one - just that it may not be trivial. But I agree with you, conceptually there should be no reason why the reader has to live for the lifetime of the program so long as it lives at least as long as the document.

**Comment by ajrcarey** [comment]
(Since PdfDocument must take ownership of the reader, it feels as though there should be no need for a lifetime specification on the reader at all - it must implicitly live as long as the PdfDocument that contains it. In practice, though, because it's created separately, Box::new() requires persuasion about the lifetime.

Now that I think about it, one solution could be to create the FpdfFileAccessExt wrapper for the reader at the same time the PdfDocument is created. I can look at this possibility in the next day or two.)

**Comment by bavardage** [comment]
I'll try to find some time to take a look this coming week too - but going to take me a bit to ramp up on the codebase. Excited to hear anything you figure out.

**Comment by bavardage** [comment]
I took a look - https://github.com/ajrcarey/pdfium-render/pull/82

**Comment by ajrcarey** [comment]
Wow! "took a look" is a slight understatement :) Thank you so much for this. The key thing you did, which I missed, was adding the 'a lifetime to 

reader: Box<dyn PdfiumDocumentReader + 'a>

in the definition of utils::FpdfFileAccessExt<'a>. I don't know why it didn't occur to me to add the lifetime there, but fortunately you were here to fix it up.

I will merge the PR and may tidy a few things up but at first glance everything looks excellent. Your work will be included in crate release 0.8.2.

**Comment by ajrcarey** [comment]
Checked changes against test suite. Removed `examples/reader.rs` in favour of inline unit test in `lib.rs`. Updated `README.md`. Changes scheduled for release in version 0.8.2.
