### ISSUE TITLE
Zero copy rendering

### ISSUE THREAD

**Issue by DorianRudolph** [ajrcarey/pdfium-render#83]
I would like to render a PdfPage into an external buffer via a raw pointer. My use case is to render directly into a skia bitmap. This way I don't have to copy the data from the PdfBitmap to the skia bitmap, saving one copy.

Right now there does not appear to be a way to give pdfium-render a pointer or slice to render into.

**Comment by ajrcarey** [comment]
Hi @DorianRudolph , yes, Pdfium does support rendering into an external buffer. We would need to add a new constructor to `PdfBitmap`. Are you wanting to provide a buffer in the form of a `&mut [u8]` slice?

(This approach is fundamentally incompatible with WASM because Pdfium and `pdfium-render` inhabit separate memory address spaces when running in the browser.)

**Comment by ajrcarey** [comment]
Under the assumption that you will be providing a `&mut [u8]`, added a new `PdfBitmap::external()` function that lets you pass in a buffer. You can test the function by using `pdfium-render` as a git dependency in your project's `Cargo.toml`.

**Comment by DorianRudolph** [comment]
Thanks, this is what I had in mind. I should be able to test it sometime this week.

Eventually I would like to get my project running in the web. Why would this not work in WASM? I guess your concern is that pdfium and pdfium-render are compiled to two different .wasm modules? I'm just learning about WASM, but could something like [this](https://gist.github.com/kfl/d5f1463ebe1b7107aeb02e2f4089a28a) work to establish a shared memory between WASM modules?

**Comment by ajrcarey** [comment]
Because Pdfium and `pdfium-render` are compiled separately, they inhabit independent WASM modules with independent linear address spaces. _In theory_ it might be possible to combine these; in practice I highly doubt it could ever work safely, because the two modules have two different memory allocators that would have no knowledge of one-another and would therefore be endlessly clobbering one another's memory allocations.

So long as the WASM memory address spaces are separate, it will never be possible to share a buffer between Pdfium and `pdfium-render` without a copy.

Because Javascript _does_ have access to all memory irrespective of WASM modules, it is possible to work around this and the `PdfBitmap::as_array()` function lets you pass through the array data of a Pdfium `FPDF_BITMAP` buffer directly to Javascript without copying it into `pdfium-render`'s address space first.

I will restrict the `PdfBitmap::external()` function to non-WASM builds only in the next commit.

You are welcome to try getting Pdfium and `pdfium-render` to share a single linear address space, but I would not be able to help you with this.

**Comment by ajrcarey** [comment]
Renamed `PdfBitmap::external()` as `PdfBitmap::from_bytes()`. Restricted compilation to non-WASM targets.

**Comment by ajrcarey** [comment]
Added unit test for `PdfBitmap::from_bytes()`. As there have been no further comments, and I believe `PdfBitmap::from_bytes()` provides the functionality you require, I am closing the issue. Feel free to reopen if you feel the issue has not been resolved.
