### ISSUE TITLE
Using custom font results in garbled, uncopyable text

### ISSUE THREAD

**Issue by stephenjudkins** [ajrcarey/pdfium-render#84]
See https://github.com/stephenjudkins/pdfium-issue for reproduction

Steps to reproduce:
1. create new PDF.
2. Add a new font to the document (this one extracted from macOS system fonts)
4. Add a new `PdfPageTextObject` using that font, with basic latin text.
5. Save the document
6. Open the document in the affected viewer and copy the text. Paste it elsewhere

Expected result: we should see the text we entered into the document. In this case `Dr. Tohichi Hikita`
Actual result: We see garbelled text with very high, unassigned unicode codepoints. Here's the text: `􏰟􏰄􏰗 􏰠􏰅􏰡􏰆􏰂􏰡􏰆 􏰢􏰆􏰣􏰆􏰃􏰊` Codepoints are like`56319, 56351, 56319,`

I have confirmed if you use a built-in font, this problem does not occur.

Viewers that are affected:
* Apple Preview
* Adobe Acrobat

Viewers that function as expected:
* Chromium
* PDF.js

I believe it is this upstream bug: https://bugs.chromium.org/p/pdfium/issues/detail?id=1690

**Comment by stephenjudkins** [comment]
Update! Specifying `false` for `is_cid_font` makes copy-pasting work but also messes up the spacing for non-ASCII symbols. I'm going to try some different fonts here.

**Comment by ajrcarey** [comment]
Hi @stephenjudkins , thank you for reporting the issue. Just be aware there will be a delay in me working on this until at least May 29.

**Comment by ajrcarey** [comment]
Yes, a test case would be useful. I'm also interested in knowing more about the exact font you're using. (Unless, of course, you see the problem with any font.)

**Comment by stephenjudkins** [comment]
I've updated the issue to reflect a minimized case.

See https://github.com/stephenjudkins/pdfium-issue/blob/master/out.pdf for the problematic result PDF.

Thank you so much for all the work you've done on this project, BTW.

**Comment by stephenjudkins** [comment]
Confirmed that this error occurs with the latest pdfium binaries from https://github.com/bblanchon/pdfium-binaries

**Comment by stephenjudkins** [comment]
Also confirmed that this error occurs with some other truetype fonts I've downloaded

**Comment by stephenjudkins** [comment]
This appears to be the upstream bug: https://bugs.chromium.org/p/pdfium/issues/detail?id=1690

**Comment by ajrcarey** [comment]
Hi @stephenjudkins , thank you for your patience. I can reproduce your problem using the Apple Preview applicaton on macOS.

I note that pdfium-render extracts the text correctly using document.pages().first()?.text()?.all().

It seems clear from your research that the problem is upstream in Pdfium itself. Are you asking for some sort of mitigation in `pdfium-render`? I'm not sure what you're asking me to do here.

**Comment by stephenjudkins** [comment]
@ajrcarey it does appear to upstream in Pdfium itself.

I'm definitely not asking you to do anything! I just put the bug in when I found it, before I did enough research to discover the likely upstream issue. I have no idea the etiquette of keeping this bug open, or closing it, or what.

I greatly appreciate your work on this library overall.

**Comment by ajrcarey** [comment]
That's completely fine. I think the thing to do is to pursue the upstream bug report and see if you can get a fix in there. (Since the problem is with rendering, I'm not sure what mitigation we could do downstream in `pdfium-render`.) This issue will remain searchable for anyone else who has the same problem to discover; for now, though, it can be closed.
